---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud9 + QuickStart VPC (Master Template) (qs-1pb4pod81)
Metadata:
  LICENSE: |-
    Copyright 2019 Amazon Web Services
    Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration (new VPC)
      Parameters:
      - AvailabilityZones
      - NumberOfAZs
      - RemoteAccessCIDR      
      - KeyPairName      
    - Label:
        default: Cloud9 Configuration
      Parameters:
      - C9InstanceType
      - C9StopTime
      - EBSVolumeSize   
    - Label:
        default: AWS Quick Start Configuration
      Parameters:
        - QSS3BucketName
        - QSS3KeyPrefix            
    ParameterLabels:
      QSS3BucketName:
        default: S3 Bucket Name
      QSS3KeyPrefix:
        default: S3 Key Prefix
      EBSVolumeSize:
        default: EBS Volume Size
      EnvironmentId:
        default: Cloud9 Instance Environment ID
      C9InstanceProfileName:
        default: Cloud9 Instance Profile Name  
      C9InstanceProfileArn:
        default: Cloud9 Instance Profile ARN
      C9InstanceType:
        default: Cloud9 Instance Type
      C9StopTime:
        default: Stop Time
      C9Subnet:
        default: Subnet ID
Parameters:
  AvailabilityZones:
    Description: >-
      List of Availability Zones to use for the subnets in the VPC. Only two
      Availability Zones are used for this deployment, and the logical order of
      your selections is preserved.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  KeyPairName:
    Description: >-
      The name of an existing public/private key pair, which allows you to
      securely connect to your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  RemoteAccessCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: >-
      The CIDR IP range that is permitted to access the instances We recommend
      that you set this value to a trusted IP range.
    Type: String      
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot
      start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-cloud9-ide/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  C9InstanceType:
    Description: The instance type of the new Amazon EC2 instance that AWS Cloud9
      will launch for the development environment (for example, 't2.micro').
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - m4.large
    - t2.nano
    - c4.large
    - t2.medium
    - t2.large
    - m4.xlarge
    - t2.xlarge
    - c4.xlarge
    - c4.2xlarge
    - m4.2xlarge
    - t2.2xlarge
    - c4.4xlarge
    - m4.4xlarge
    - c4.8xlarge
    - m4.10xlarge
    - m4.16xlarge
  C9StopTime:
    Description: The number of minutes until the running instance is shut down after
      the environment has last been used.
    Type: Number
    Default: 30
  EBSVolumeSize:
    Description: The desired size (GB) of the EBS volume for your Cloud9 IDE.
    Type: Number
    Default: 100
Resources: 
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template
      Parameters:
        AvailabilityZones: !Join 
          - ','
          - !Ref AvailabilityZones
        CreatePrivateSubnets: 'false'
        KeyPairName: !Ref KeyPairName
        PublicSubnet1CIDR: "10.0.128.0/20"
        PublicSubnet2CIDR: "10.0.144.0/20"
        NumberOfAZs: '2'
  IDEStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub >-
        https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/cloud9-ide-instance.yaml
      Parameters:
        C9InstanceType: !Ref 'C9InstanceType'
        C9StopTime: !Ref 'C9StopTime'
        C9Subnet: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
